apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: open-cicada-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: open-cicada-python 
  name: open-cicada-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: open-cicada-python 
